### ISSUE TITLE
Name of the library

### ISSUE THREAD

**Issue by tomkis1** [salsita/prism#35]
When I was presenting `redux-elm` @ reactive vienna I guess that @ryyppy had a good point about inconsistency between `redux-elm` and elm 17+ which has removed some concepts (FRP) and did slight changes in component composition. Function `forwardTo` has been removed and replaced by `App.map` which goal is technically still the same.

Anyway, after re-thinking everything we can now declare that `redux-elm` and `elm` shares just idea of fractability by utilizing component composition. This is hardly the most important part of Elm.

The long term goal has always been renaming the library and distancing from original Elm architecture since we don't want to blindly copy what already exists.

I filed this issue and would appreciate any feedback on this + possible name suggestions.

**Comment by eliperelman** [comment]
Is the goal to have the library name still be `redux-*` or completely abstract?

**Comment by tomkis1** [comment]
Yes that's the goal. We were thinking of `redux-fractal`.

**Comment by stratospark** [comment]
Great library! Here are some ideas:

**redux-wrap**
**redux-nested**

Here's a wild one: **refrakt**! Unfortunately, refract is already taken: https://www.npmjs.com/package/refract

**Comment by tomkis1** [comment]
I really like **refract** and because it looks like the name is taken by some active library we might want to use name **refractor** which [is obviously taken too](https://github.com/kpdecker/refractor) however the repo doesn't seem very active.

**Comment by eliperelman** [comment]
How about then **refractal**?

**Comment by jmarceli** [comment]
Or maybe **reactal**.

**Comment by ghola** [comment]
Fractal is about symmetry: **resym**

**Comment by ghola** [comment]
Fractal is about a pattern that repeats itself: **repattern**, **repat**

**Comment by tomkis1** [comment]
Library has been renamed to `prism` not `redux-prism` since technically it's not related only to redux but react as well.

**Comment by jmarceli** [comment]
@tomkis are you sure that `prism` is the right naming choice? There is already well known http://prismjs.com/ library which will make any topic related to this repository hard to find with Google.
