### ISSUE TITLE
Switch to standard boilerplate

### ISSUE THREAD

**Issue by dalgard** [salsita/prism#53]
Trying to hide boilerplate code behind a custom `run` function in the examples does more harm than good, in my opinion.

It makes everything less easy to understand when one is used to reading other examples, and disentangling the `run` pattern in order to incorporate `redux-elm` into a more customized setup is a bit of a nuisance.

I propose that the examples be changed to standard React + Redux boilerplate.

**Comment by tomkis1** [comment]
I always found those boilerplates way too "blackbox". For me I prefer full control over the code **and** boilerplate. Maybe we could have examples for both?

**Comment by dalgard** [comment]
What you're saying sounds exactly like my argument? The `run` function is a black box, which takes away my control over the code.

It's not a difficult task to unravel your code, it's just that one would expect for users of `redux-elm` to be very familiar with the standard boilerplate for React + Redux projects – and not with your custom implementation, which consequently introduces some cognitive overhead that ought to have been avoided.

**Comment by tomkis1** [comment]
> What you're saying sounds exactly like my argument? The run function is a black box, which takes away my control over the code.

Oh yeah sure, my point was that this boilerplate should be *very* minimalistic so that everybody can understand what's going on under the hood. Maybe we could document the function better.

**Comment by kdalgaard** [comment]
Definitely, Less is more.

**Comment by tomkis1** [comment]
Closing, there's no additional boilerplate need. Redux-elm aka. prism is now just a set of helpers.
