### ISSUE TITLE
Reduce bundle size by using rxjs modularity

### ISSUE THREAD

**Issue by gadyonysh** [salsita/prism#66]
Hello,

I want to reduce my app bundle size and not to include all rxjs in redux-elm sagas implementation.
I've replaced in RxjsSaga.js and ReduxSaga.js
`import { Subject } from 'rxjs';`
with
`import { Subject } from 'rxjs/Subject';`
as described [here](https://github.com/ReactiveX/rxjs)
After that my app bundle size reduced by ~186kB with no changes in functionality.

Do we really need to include all rxjs inside redux-elm?

**Comment by tomkis1** [comment]
Rxjs is not part of redux-elm (prism) anymore.
