### ISSUE TITLE
redux-saga update

### ISSUE THREAD

**Issue by krzysztofpniak** [salsita/prism#71]
Please update peerDependency of redux-saga, current version does not contain some useful helpers like throttle.

**Comment by tomkis1** [comment]
Could you please file a PR? I am actually in the middle of complete rewrite. Which could potentially help solve all the pain points with current approach. Unfortunately, there will be breaking changes.

**Comment by tomkis1** [comment]
In version 4.x we no longer rely on `redux-saga`.
