### ISSUE TITLE
Where is documentation for v3?

### ISSUE THREAD

**Issue by krzysztofpniak** [salsita/prism#77]
I'm using redux-elm in 4 production applications. I'm not going to switch to prism soon, because I do not have time for this. I think you shouldn't just remove docs to v3, because you released whole new product. Better option is to left old one with information that it is deprecated.

Regards
Krzysztof

**Comment by eliperelman** [comment]
Looking at the v3.1.0 tag, it appears that the docs are still there:

https://github.com/salsita/prism/tree/v3.1.0/docs

**Comment by tomkis1** [comment]
Yes, the whole history is still findable on git.
